---
# defaults file for deploy-impairment-workers
ansible_python_interpreter: /usr/bin/python3.8

duration: 30 # seconds
startDelay: 5 # seconds. It typically takes about 2-3 seconds for the Daemonset to run
interfaces:
- "ens2f0"

# Both ingress and egress
bandwidth: 0 # kbit
latency: 0 # latency
loss: 0 # percent

# ingress and egress overwrite the bidirectional
ingress: # uses ifb
  bandwidth: 0 # kbit
  latency: 0 # ms
  loss: 0 # percent
egress:
  bandwidth: 0 #kbit
  latency: 0 # ms
  loss: 0 # percent

linkFlapping:
  enable: false
  downTime: 3
  upTime: 3

