apiVersion: apps.redhat.com/v1alpha1
kind: ClusterImpairment
metadata:
  name: duplication
spec:
  duration: 60
  startDelay: 5
  interfaces:
  - "ens3"
  ingress:
    duplication: 25 # percent
  egress:
    duplication: 25 # percent
