apiVersion: apps.redhat.com/v1alpha1
kind: ClusterImpairment
metadata:
  name: test-impairment-cr
spec:
  duration: 30 # seconds
  startDelay: 5 # seconds. It typically takes about 2-3 seconds for the Daemonset to run
  interfaces:
  - "ens2f0"
  ingress: # uses ifb
    bandwidth: 0 # kbit
    latency: 10 # ms
    loss: 0 # percent
  egress:
    bandwidth: 0 #kbit
    latency: 100 # ms
    loss: 0 # percent
  linkFlapping:
    enable: false
    downTime: 3
    upTime: 3
  nodeSelector:
    key: "node-role.kubernetes.io/worker"
    value: ""
