apiVersion: apps.redhat.com/v1alpha1
kind: ClusterImpairment
metadata:
  name: uneven-latency
spec:
  duration: 60
  startDelay: 5
  interfaces:
  - "ens2f0"
  ingress:
    latency: 10 # ms
  egress:
    latency: 100 # ms
  nodeSelector:
    key: "node-role.kubernetes.io/worker"
    value: ""

