apiVersion: apps.redhat.com/v1alpha1
kind: ClusterImpairment
metadata:
  name: two-min-flap
spec:
  duration: 480
  startDelay: 5
  interfaces:
  - "ens3"
  linkFlapping:
    enable: true
    downTime: 12 # Seconds
    upTime: 12 # Seconds

