apiVersion: v1
kind: Namespace
metadata:
  name: cluster-impairment-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: network-access-sa
  namespace: cluster-impairment-operator
---
kind: SecurityContextConstraints
metadata:
  creationTimestamp: null
  name: network-access-all
allowHostDirVolumePlugin: true
allowHostIPC: false
allowHostNetwork: true
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: true
allowedCapabilities: []
apiVersion: security.openshift.io/v1
defaultAddCapabilities: []
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities: []
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
users:
- system:serviceaccount:cluster-impairment-operator:network-access-sa
